# fly.toml app configuration file generated for cec-datingapp on 2023-06-23T15:37:09+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "cec-datingapp"
primary_region = "arn"

[build]
  image = "cecvage/datingapp:latest"

[env]
  ASPNETCORE_URLS="http://+:8080"
  CloudinarySettings__CloudName="dblpnyz9h"
  CloudinarySettings__ApiKey="453175152585951"

[http_service]
  http_checks = []
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
